// Bell pulses: the fractal's surface lifts and glows where each bell sounds. Driven by the exact event
// times in frames.json (generated by tools/sounds/frames.mjs from the same pattern the audio was rendered
// from), not by guessing from the audio spectrum, so a pulse starts on the frame the bell starts.
//
// Pure functions of time: Remotion renders frames independently and out of order, so nothing here carries
// state between frames.

export const BELL_LAYER = '$3'; // the `$:` layer of the bells voice in slow-drift.strudel
export const MAX_ACTIVE = 6; // matches uBells[6] in shaders.ts
const REFERENCE_GAIN = 0.08; // the loudest bell gain in the piece (climax)
const LIFETIME_SECONDS = 10; // the bell's reverb/delay tail, past which a pulse is invisible

export type BellHit = { seconds: number; x: number; y: number; amp: number };

type RawEvent = { layer: string; seconds: number; value: { note?: number; gain?: number; pan?: number } };

// Each bell is two stacked layers with the same note (primary + a quieter one at half gain): keep one hit
// per onset time, the louder one. Position: horizontal from the bell's own stereo pan (the sound and the
// glow sit at the same place), vertical from its pitch (higher note, higher on screen). Screen units are
// the shader's `base` space: x within about +/-0.89, y within +/-0.5.
export function parseBellHits(events: RawEvent[]): BellHit[] {
  const byTime = new Map<number, RawEvent>();
  for (const e of events) {
    if (e.layer !== BELL_LAYER) continue;
    const prev = byTime.get(e.seconds);
    if (!prev || (e.value.gain ?? 0) > (prev.value.gain ?? 0)) byTime.set(e.seconds, e);
  }
  return [...byTime.values()]
    .sort((a, b) => a.seconds - b.seconds)
    .map((e) => {
      const pan = e.value.pan ?? 0.5;
      const note = e.value.note ?? 78;
      return {
        seconds: e.seconds,
        x: (pan - 0.5) * 1.5,
        y: Math.max(-1, Math.min(1, (note - 78) / 6)) * 0.26,
        amp: Math.max(0.5, Math.min(1, (e.value.gain ?? REFERENCE_GAIN) / REFERENCE_GAIN)),
      };
    });
}

// Flat Float32Array of MAX_ACTIVE vec4s (x, y, age in seconds, amp); unused slots have amp 0.
export function activeBells(hits: BellHit[], t: number): Float32Array {
  const out = new Float32Array(MAX_ACTIVE * 4);
  let n = 0;
  for (let i = hits.length - 1; i >= 0 && n < MAX_ACTIVE; i--) {
    const age = t - hits[i].seconds;
    if (age < 0) continue;
    if (age > LIFETIME_SECONDS) break;
    out.set([hits[i].x, hits[i].y, age, hits[i].amp], n * 4);
    n++;
  }
  return out;
}
